# 1 "../src/audio/simple_loudmeter.c"
# 1 "C:\\Users\\i69379\\OneDrive - Microchip Technology Inc\\Desktop\\perseus_512\\perseus_512.X//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "../src/audio/simple_loudmeter.c"
